#!/bin/sh
set -e

# 9.1.4-2 moved pg_basebackup manpage from server to client; we need to rebuild
# the alternatives for postmaster to drop pg_basebackup.1.gz from the group
if [ "$1" = "upgrade" ] || [ "$1" = "install" ] && \
	dpkg --compare-versions "$2" lt-nl "9.1.4-2~"; then
    update-alternatives --remove postmaster.1.gz /usr/share/postgresql/9.1/man/man1/postmaster.1.gz
fi

#DEBHELPER#

exit 0
